#!/bin/bash

CHECKS=clang-diagnostic-*,clang-analyzer-*,cppcoreguidelines-*,modernize-*,-clang-analyzer-osx*,misc-,performance-*,readability-*,bugprone-*,-clang-diagnostic-c++11-extensions*

clang-tidy -quiet -header-filter="./" -checks="$CHECKS" test/test.cpp -- -std=c++17 -I ./include 2>/dev/null
